[project]
name = "community-notebook-competition"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "jsonschema>=4.25.1",
    "python-frontmatter>=1.1.0",
]
