name: Validate submission.ipynb

on:
  pull_request:
    paths:
      - 'submissions/**'

jobs:
  validate-submission:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read

    steps:
      - name: Check out PR code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install uv
        uses: astral-sh/setup-uv@v6

      - name: Sync
        run: |
          uv sync

      - name: Find changed submission.ipynb path in PR
        id: find_submission
        uses: actions/github-script@v7
        with:
          script: |
            const owner = context.repo.owner;
            const repo = context.repo.repo;
            const number = context.payload.pull_request.number;

            const files = await github.paginate(
              github.rest.pulls.listFiles,
              { owner, repo, pull_number: number, per_page: 100 }
            );

            const candidates = files
              .map(f => f.filename)
              .filter(p => /(^|\/)submission\.ipynb$/i.test(p));

            if (candidates.length === 0) {
              core.setFailed("No file named 'submission.ipynb' was changed in this PR.");
              return;
            }
            if (candidates.length > 1) {
              core.setFailed(`Multiple 'submission.ipynb' files found: ${candidates.join(", ")}`);
            }

            core.setOutput("path", candidates[0]);

      - name: Lint submission.ipynb
        run: |
          uv run nbqa ruff ${{ steps.find_submission.outputs.path }}
